[package]
name = "ditherer"
version = "0.1.4"
edition = "2021"
description = "Fun little Bayer matrix ditherer in Rust."
license = "MIT"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
image = "0.25.5"
